using FluentAssertions;
using VideoSplitJoiner.Core.Ffmpeg;
using VideoSplitJoiner.Core.Thumbnails;
using Xunit;
using Xunit.Abstractions;

namespace VideoSplitJoiner.Core.Tests;

/// <summary>
/// T-179 / G-058 real-environment exit probe for <see cref="FfmpegThumbnailService"/>: real ffmpeg on a
/// synthetic testsrc clip the test run generates (never a user file), a temp cache root, and the real
/// <see cref="FfmpegRunner"/> behind a counting decorator. It reads each picture's REAL pixel width from
/// the JPEG header — the check T-172's acceptance test could not make, because it ran against a cache-less
/// fake while production handed back cached 64px frames.
/// </summary>
[Collection(MediaFixturesCollection.Name)]
public sealed class FfmpegThumbnailServiceIntegrationTests : IDisposable
{
    private readonly MediaFixtures _fixtures;
    private readonly ITestOutputHelper _output;

    private readonly string _cacheRoot = Path.Combine(
        Path.GetTempPath(), "vsj-thumb-real-" + Guid.NewGuid().ToString("N"));

    public FfmpegThumbnailServiceIntegrationTests(MediaFixtures fixtures, ITestOutputHelper output)
    {
        _fixtures = fixtures;
        _output = output;
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_cacheRoot))
            {
                Directory.Delete(_cacheRoot, recursive: true);
            }
        }
        catch
        {
            // Best-effort cleanup.
        }
    }

    // SPEC-005#I26 — the same second grabbed at 64, then 640, then 64 again yields pictures that really
    // are 64, 640 and 64 pixels wide, with two ffmpeg runs (the third call is a hit for its own width).
    // Before T-179 the widths read 64, 64, 64 and ffmpeg ran once.
    [Trait("serves-spec", "SPEC-005")]
    [SkippableFact]
    public async Task GetThumbnailAsync_RealFfmpeg_EachWidthIsReallyThatWide()
    {
        FfmpegTestBinaries.Require(_output, FfmpegTestBinaries.FfmpegExists, "ffmpeg");

        var clip = _fixtures.VideoOnlyPath; // 10 s testsrc, generated by the test run
        var runner = new CountingRunner(
            new FfmpegRunner(new FfmpegBinaryLocator(ffmpegOverride: FfmpegTestBinaries.FfmpegRequired)));
        var service = new FfmpegThumbnailService(runner, _cacheRoot);

        var chip = await service.GetThumbnailAsync(clip, TimeSpan.FromSeconds(2), 64, CancellationToken.None);
        var picture = await service.GetThumbnailAsync(clip, TimeSpan.FromSeconds(2), 640, CancellationToken.None);
        var chipAgain = await service.GetThumbnailAsync(clip, TimeSpan.FromSeconds(2), 64, CancellationToken.None);

        chip.Should().NotBeNull();
        picture.Should().NotBeNull();
        chipAgain.Should().NotBeNull();

        var widths = new[] { chip!, picture!, chipAgain! }.Select(JpegWidth.Read).ToArray();
        _output.WriteLine($"real widths: {string.Join(", ", widths)} · ffmpeg runs: {runner.CallCount}");

        widths.Should().Equal(64, 640, 64);
        runner.CallCount.Should().Be(2, "the third call is a cache hit for its own width");
    }

    /// <summary>Decorates the real runner with a run counter.</summary>
    private sealed class CountingRunner : IFfmpegRunner
    {
        private readonly IFfmpegRunner _inner;

        public CountingRunner(IFfmpegRunner inner) => _inner = inner;

        public int CallCount { get; private set; }

        public Task<FfmpegResult> RunAsync(
            FfmpegArgs args,
            TimeSpan? totalDuration = null,
            IProgress<double>? progress = null,
            CancellationToken ct = default)
        {
            CallCount++;
            return _inner.RunAsync(args, totalDuration, progress, ct);
        }
    }
}

/// <summary>
/// Reads a JPEG's pixel width from its start-of-frame (SOFn) segment. Core.Tests stays WPF-free, so this
/// walks the marker segments instead of decoding the picture.
/// </summary>
internal static class JpegWidth
{
    public static int Read(string path)
    {
        var bytes = File.ReadAllBytes(path);
        if (bytes.Length < 4 || bytes[0] != 0xFF || bytes[1] != 0xD8)
        {
            throw new InvalidDataException($"{path} is not a JPEG (no SOI marker).");
        }

        var i = 2;
        while (i + 4 <= bytes.Length)
        {
            if (bytes[i] != 0xFF)
            {
                i++;
                continue;
            }

            var marker = bytes[i + 1];
            if (marker is 0xFF)
            {
                i++;
                continue;
            }

            // Standalone markers carry no length.
            if (marker is 0x01 or (>= 0xD0 and <= 0xD7))
            {
                i += 2;
                continue;
            }

            var length = (bytes[i + 2] << 8) | bytes[i + 3];

            // SOF0..SOF15, except DHT (C4), JPG (C8) and DAC (CC): [len:2][precision:1][height:2][width:2].
            if (marker is >= 0xC0 and <= 0xCF and not 0xC4 and not 0xC8 and not 0xCC)
            {
                return (bytes[i + 7] << 8) | bytes[i + 8];
            }

            i += 2 + length;
        }

        throw new InvalidDataException($"{path} has no start-of-frame segment.");
    }
}
