using FluentAssertions;
using VideoSplitJoiner.Core.Ffmpeg;
using VideoSplitJoiner.Core.Media;
using Xunit;
using Xunit.Abstractions;

namespace VideoSplitJoiner.Core.Tests;

/// <summary>
/// Integration tests for <see cref="MediaProbe"/> against synthetic mp4 fixtures with KNOWN
/// keyframe positions, generated by the real ffmpeg. Guarded to skip-with-message when the
/// ffmpeg/ffprobe binaries are absent.
/// </summary>
[Collection(MediaFixturesCollection.Name)]
public class MediaProbeIntegrationTests
{
    private readonly MediaFixtures _fixtures;
    private readonly ITestOutputHelper _output;

    public MediaProbeIntegrationTests(MediaFixtures fixtures, ITestOutputHelper output)
    {
        _fixtures = fixtures;
        _output = output;
    }

    private static MediaProbe MakeProbe() =>
        new(new FfprobeRunner(new FfmpegBinaryLocator(ffprobeOverride: FfmpegTestBinaries.Ffprobe)));

    private bool ShouldSkip()
    {
        // Needs BOTH ffprobe (to probe) and ffmpeg (to generate fixtures).
        if (FfmpegTestBinaries.SkipIfMissing(_output, FfmpegTestBinaries.FfprobeExists, "ffprobe"))
        {
            return true;
        }

        return FfmpegTestBinaries.SkipIfMissing(_output, MediaFixtures.FfmpegAvailable, "ffmpeg");
    }

    [Fact]
    public async Task ProbeAsync_AvFixture_ReportsDurationStreamsAndContainer()
    {
        if (ShouldSkip())
        {
            return;
        }

        var probe = MakeProbe();
        var result = await probe.ProbeAsync(_fixtures.VideoWithAudioPath);

        result.IsSuccess.Should().BeTrue();
        var info = ((ProbeResult.ProbeSucceeded)result).Info;

        info.Duration.Should().BeCloseTo(TimeSpan.FromSeconds(10), TimeSpan.FromMilliseconds(200));
        info.Container.Should().MatchRegex("mp4|mov");
        info.HasVideo.Should().BeTrue();

        info.VideoStreams.Should().ContainSingle();
        var v = info.VideoStreams[0];
        v.CodecName.Should().Be("h264");
        v.Width.Should().Be(320);
        v.Height.Should().Be(240);
        v.PixFmt.Should().NotBeNullOrEmpty();

        info.AudioStreams.Should().ContainSingle();
        var a = info.AudioStreams[0];
        a.CodecName.Should().Be("aac");
        a.SampleRate.Should().BePositive();
        a.Channels.Should().BePositive();
    }

    [Fact]
    public async Task ProbeAsync_NonMediaFile_ReturnsProbeFailed_NoException()
    {
        if (ShouldSkip())
        {
            return;
        }

        var bogus = Path.Combine(Path.GetTempPath(), "vsj-bogus-" + Guid.NewGuid().ToString("N") + ".mp4");
        await File.WriteAllTextAsync(bogus, "not a video");
        try
        {
            var probe = MakeProbe();
            var result = await probe.ProbeAsync(bogus);

            result.IsSuccess.Should().BeFalse();
            result.Should().BeOfType<ProbeResult.ProbeFailed>();
            ((ProbeResult.ProbeFailed)result).Reason.Should().NotBeNullOrWhiteSpace();
        }
        finally
        {
            File.Delete(bogus);
        }
    }

    [Fact]
    public async Task GetKeyframesAsync_Fixture_SortedAscending_SpacingAboutOneSecond()
    {
        if (ShouldSkip())
        {
            return;
        }

        var probe = MakeProbe();
        var kf = await probe.GetKeyframesAsync(_fixtures.VideoOnlyPath);

        kf.Should().NotBeEmpty();
        kf.Should().BeInAscendingOrder();
        kf.Count.Should().BeInRange(10, 12);
        kf[0].Should().BeCloseTo(TimeSpan.Zero, TimeSpan.FromMilliseconds(50));

        var gop = probe.AverageGop(kf);
        _output.WriteLine($"observed keyframe count={kf.Count}, avg GOP={gop.TotalSeconds:F3}s");
        gop.Should().BeCloseTo(TimeSpan.FromSeconds(1.0), TimeSpan.FromMilliseconds(100));
    }

    [Fact]
    public async Task SnapToNearestKeyframe_AgainstRealFixture_SnapsToWholeSeconds()
    {
        if (ShouldSkip())
        {
            return;
        }

        var probe = MakeProbe();
        var kf = await probe.GetKeyframesAsync(_fixtures.VideoOnlyPath);

        var snap = probe.SnapToNearestKeyframe(kf, TimeSpan.FromSeconds(3.4));
        snap.Snapped.Should().BeCloseTo(TimeSpan.FromSeconds(3.0), TimeSpan.FromMilliseconds(50));

        var snap2 = probe.SnapToNearestKeyframe(kf, TimeSpan.FromSeconds(3.6));
        snap2.Snapped.Should().BeCloseTo(TimeSpan.FromSeconds(4.0), TimeSpan.FromMilliseconds(50));
    }

    [Fact]
    public async Task GetKeyframesAsync_SecondCall_ReturnsSameList_FromCache()
    {
        if (ShouldSkip())
        {
            return;
        }

        var probe = MakeProbe();
        var first = await probe.GetKeyframesAsync(_fixtures.VideoOnlyPath);
        var second = await probe.GetKeyframesAsync(_fixtures.VideoOnlyPath);

        second.Should().Equal(first);
    }
}
