using FluentAssertions;
using VideoSplitJoiner.Core.Detect;
using VideoSplitJoiner.Core.Ffmpeg;
using VideoSplitJoiner.Core.Media;
using Xunit;
using Xunit.Abstractions;

namespace VideoSplitJoiner.Core.Tests;

/// <summary>
/// Integration tests for <see cref="SplitPointDetector"/> against a synthetic mp4 with KNOWN
/// black / white / scene events, generated by the real ffmpeg. Guarded to skip-with-message
/// when the ffmpeg/ffprobe binaries are absent.
/// </summary>
[Collection(DetectFixturesCollection.Name)]
public class SplitPointDetectorIntegrationTests
{
    private readonly DetectFixtures _fixtures;
    private readonly ITestOutputHelper _output;

    public SplitPointDetectorIntegrationTests(DetectFixtures fixtures, ITestOutputHelper output)
    {
        _fixtures = fixtures;
        _output = output;
    }

    private static SplitPointDetector MakeDetector()
    {
        var locator = new FfmpegBinaryLocator(
            ffmpegOverride: FfmpegTestBinaries.Ffmpeg,
            ffprobeOverride: FfmpegTestBinaries.Ffprobe);
        var runner = new FfmpegRunner(locator);
        var probe = new MediaProbe(new FfprobeRunner(locator));
        return new SplitPointDetector(runner, probe, locator);
    }

    private static MediaProbe MakeProbe() =>
        new(new FfprobeRunner(new FfmpegBinaryLocator(ffprobeOverride: FfmpegTestBinaries.Ffprobe)));

    private bool ShouldSkip()
    {
        if (FfmpegTestBinaries.SkipIfMissing(_output, FfmpegTestBinaries.FfmpegExists, "ffmpeg"))
        {
            return true;
        }

        return FfmpegTestBinaries.SkipIfMissing(_output, FfmpegTestBinaries.FfprobeExists, "ffprobe");
    }

    [Fact]
    public async Task DetectAsync_EventFixture_FindsBlackWhiteAndScene_RankedAndSnapped()
    {
        if (ShouldSkip())
        {
            return;
        }

        var detector = MakeDetector();
        var candidates = await detector.DetectAsync(_fixtures.EventsPath, new DetectOptions(), progress: null);

        candidates.Should().NotBeEmpty();
        foreach (var c in candidates)
        {
            _output.WriteLine($"rank={c.Rank} kind={c.Kind} t={c.Time.TotalSeconds:F3} snapped={c.SnappedTime.TotalSeconds:F3} score={c.Score:F3}");
        }

        // --- Each kind present. ---
        candidates.Should().Contain(c => c.Kind == CandidateKind.Black);
        candidates.Should().Contain(c => c.Kind == CandidateKind.White);
        candidates.Should().Contain(c => c.Kind == CandidateKind.Scene);

        // --- Black near ~2.0s (±0.4s), White near ~5.5s (±0.4s), a Scene near a boundary. ---
        candidates.Should().Contain(c =>
            c.Kind == CandidateKind.Black
            && Math.Abs(c.Time.TotalSeconds - DetectFixtures.BlackStartSeconds) <= 0.4);

        candidates.Should().Contain(c =>
            c.Kind == CandidateKind.White
            && Math.Abs(c.Time.TotalSeconds - DetectFixtures.WhiteStartSeconds) <= 0.4);

        candidates.Should().Contain(c =>
            c.Kind == CandidateKind.Scene
            && (NearAny(c.Time.TotalSeconds, 2.0, 3.5, 5.5, 7.0)));

        // --- Ranked: ranks are 1..N ascending & unique; scores are non-increasing with rank. ---
        candidates.Select(c => c.Rank).Should().Equal(Enumerable.Range(1, candidates.Count));
        for (var i = 1; i < candidates.Count; i++)
        {
            candidates[i].Score.Should().BeLessThanOrEqualTo(candidates[i - 1].Score + 1e-9);
        }

        // --- Snapped: every SnappedTime is an actual keyframe of the fixture. ---
        var probe = MakeProbe();
        var keyframes = await probe.GetKeyframesAsync(_fixtures.EventsPath);
        keyframes.Should().NotBeEmpty();
        foreach (var c in candidates)
        {
            keyframes.Should().Contain(k => k == c.SnappedTime,
                $"candidate at {c.Time.TotalSeconds:F3}s snapped to {c.SnappedTime.TotalSeconds:F3}s must be a keyframe");
        }
    }

    [Fact]
    public async Task DetectAsync_BusyFixture_NoBlackOrWhite_DoesNotErrorOrHang()
    {
        if (ShouldSkip())
        {
            return;
        }

        var detector = MakeDetector();

        // Plain testsrc: no fades. An empty candidate list is a valid result, not an exception.
        var candidates = await detector.DetectAsync(_fixtures.BusyOnlyPath, new DetectOptions(), progress: null);

        candidates.Should().NotContain(c => c.Kind == CandidateKind.Black);
        candidates.Should().NotContain(c => c.Kind == CandidateKind.White);
        // Scene or empty — both acceptable; ranks stay well-formed if present.
        candidates.Select(c => c.Rank).Should().Equal(Enumerable.Range(1, candidates.Count));
        _output.WriteLine($"busy-fixture candidate count = {candidates.Count}");
    }

    [Fact]
    public async Task DetectAsync_MaxCandidatesCap_Respected()
    {
        if (ShouldSkip())
        {
            return;
        }

        var detector = MakeDetector();
        var options = new DetectOptions(MaxCandidates: 2);

        var candidates = await detector.DetectAsync(_fixtures.EventsPath, options, progress: null);

        candidates.Count.Should().BeLessThanOrEqualTo(2);
        candidates.Select(c => c.Rank).Should().Equal(Enumerable.Range(1, candidates.Count));
    }

    [Fact]
    public async Task DetectAsync_ReportsProgress_ReachesOne()
    {
        if (ShouldSkip())
        {
            return;
        }

        var detector = MakeDetector();
        var seen = new List<double>();
        var progress = new Progress<double>(p =>
        {
            lock (seen)
            {
                seen.Add(p);
            }
        });

        await detector.DetectAsync(_fixtures.EventsPath, new DetectOptions(), progress);

        // Give the Progress<T> synchronization-context callbacks a moment to drain.
        await Task.Delay(50);
        lock (seen)
        {
            seen.Should().NotBeEmpty();
            seen.Should().OnlyContain(p => p >= 0.0 && p <= 1.0 + 1e-9);
            seen.Should().Contain(p => p >= 0.999); // final Report(1.0)
        }
    }

    private static bool NearAny(double value, params double[] targets) =>
        targets.Any(t => Math.Abs(value - t) <= 0.4);
}
