<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>VideoSplitJoiner.Core</RootNamespace>
    <AssemblyName>VideoSplitJoiner.Core</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VideoSplitJoiner.Core.Tests" />
  </ItemGroup>

</Project>
